[package]
name = "pin-scoped"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.30"
parking_lot_core = "0.9.10"
pin-project = "1.1.5"
pinned-aliasable = "0.1.3"
tokio = { version = "1.37.0", default-features = false, features = ["rt", "rt-multi-thread"] }
async_fn_traits = "0.1.1"

[dev-dependencies]
tokio = { version = "1.37.0", default-features = false, features = ["macros", "time"] }
trybuild = "1.0.96"
