[package]
name = "pin-scoped"
version = "0.1.0"
edition = "2021"

[dependencies]
pin-project-lite = "0.2"
pinned-aliasable = "0.1.3"
tokio = { version = "1.37.0", default-features = false, features = ["rt", "rt-multi-thread"] }

[dev-dependencies]
futures-util = "0.3.30"
tokio = { version = "1.37.0", default-features = false, features = ["macros", "time"] }
trybuild = "1.0.96"

[target.'cfg(loom)'.dependencies]
loom = { version = "0.7", features = ["futures"] }
tokio = { version = "1.37.0", default-features = false, features = ["sync"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }
